### ISSUE TITLE
Code for ESPHome

### ISSUE THREAD

**Issue by PiteousHonking** [Mottramlabs/4-Channel-Mains-Current-Sensor#2]
Here is the YAML to enable this board to work in ESPhome. You will need to change the filters when you calibrate your own STC

```
i2c:
  sda: 4
  scl: 5
  scan: true

ads1115:
  - address: 0x48
    continuous_mode: on
sensor:
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 2.048
    name: "ADS1115 Channel A0-GND"
    id: ads_sensor0
    
  - platform: ct_clamp
    sensor: ads_sensor0
    name: "Current Sensor Channel 1"
    update_interval: 10s
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0 -> 0
          # Known load: 7.73A
          # Value shown in logs: 0.057A
          - 0.057 -> 7.73    

  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 2.048
    name: "ADS1115 Channel A1-GND"
    id: ads_sensor1
    
  - platform: ct_clamp
    sensor: ads_sensor1
    name: "Current Sensor Channel 2"
    update_interval: 10s
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0 -> 0
          # Known load: 7.73A
          # Value shown in logs: 0.057A
          - 0.057 -> 7.73
    
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 2.048
    name: "ADS1115 Channel A2-GND"
    id: ads_sensor2

  - platform: ct_clamp
    sensor: ads_sensor2
    name: "Current Sensor Channel 3"
    update_interval: 10s
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0 -> 0
          # Known load: 7.73A
          # Value shown in logs: 0.057A
          - 0.057 -> 7.73


  - platform: ads1115
    multiplexer: 'A3_GND'
    gain: 2.048
    name: "ADS1115 Channel A3-GND"
    id: ads_sensor3
    
  - platform: ct_clamp
    sensor: ads_sensor3
    name: "Current Sensor Channel 4"
    update_interval: 10s
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0 -> 0
          # Known load: 7.73A
          # Value shown in logs: 0.057A
          - 0.057 -> 7.73




```
